services:
  - type: web
    name: nmtv-backend
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: YOUTUBE_API_KEY
        sync: false
      - key: IMVDB_API_KEY
        sync: false
      - key: FRONTEND_URL
        sync: false
      - key: PORT
        value: 3001
